name: Android Build

on:
  push:
    branches: ["dev"]
  release:
    types: [published]

jobs:
  android_build:
    name: Android Build
    runs-on: ubuntu-latest
    steps:
      name: Checkout
      - uses: actions/checkout@v2

      name: Setup Node
      - uses: actions/setup-node@master

      name: Setup Yarn Cache
      - uses: c-hive/gha-yarn-cache@v1

      # Install node modules
      run: |
        yarn install

      # Runs Testing
      run: |
        yarn test-ci

      # Cache Gradle Wrapper
      uses: actions/cache@v2
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      # Cache Gradle Dependencies
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-caches-

      # Make Gradlew Executable
      run: cd android && chmod +x ./gradlew

      # Build Android App Bundle
      run: |
        cd android && ./gradlew bundleRelease --no-daemon

    # TO ADD - ANDROID SIGN EDIT

      # Upload Artifact
      uses: actions/upload-artifact@v2

     # TO ADD - ANDROID SIGN EDIT