name: Android Build

on:
  push:
    branches: ["dev", "depf-*"]
  release:
    types: [published]

jobs:
  android_build:
    name: Android Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: 20.x
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: |
          eas build --local \
            --output= ./app-build/depfitness-build-android.apk \
            --non-interactive \
            --platform android 

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: ./app-build