name: Android Release Build

on:
  push:
    tags:
      - 'v*'

jobs:
  android_build:
    name: Android Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: 20.x
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Create env file
        run: |
          touch .env
          echo FIREBASE_API_KEY="${{ secrets.FIREBASE_API_KEY }}" > .env
          echo FIREBASE_APP_ID="${{ env.FIREBASE_APP_ID }}" > .env
          echo FIREBASE_MEASUREMENT_ID="${{ env.FIREBASE_MEASUREMENT_ID }}" > .env
          echo FIREBASE_PROJECT_ID="${{ env.PROJECT_ID }}" > .env
          echo FIREBASE_SENDER_ID="${{ env.FIREBASE_SENDER_ID }}" > .env

      - name: Build app
        run: |
          eas build --local --non-interactive \
          --platform android --profile dev \
          --output=./app-build \

      - name: Rename file
        run: mv ./app-build app-build.apk
            
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: depfitness-build-android
          path: ./app-build.apk
  
  make_release:
    name: Create Release
    needs: android_build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifact
        id: download-artifact
        uses: actions/download-artifact@v3
        with:
          name: depfitness-build-android

      - name: Archive content
        uses: thedoctor0/zip-release@master
        with:
          filename: depfitness-build-android.zip

      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Additions and Changes for this Release:
            - TBA
          draft: false
          prerelease: false
      
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./depfitness-build-android.zip
          asset_name: depfitness-build-android-v${{ github.ref }}.zip
          asset_content_type: application/zip